### PR TITLE
Add travis test

### PR DESCRIPTION
**Pull request by fengmk2**
Also fix typo on nodeDistUrl

### CODE REVIEW

**Comment by fengmk2** [comment]
My pr bring the bug here https://github.com/mafintosh/node-gyp-install/commit/ca5a9bd693f5994890a1a97964319d600451ac0c#diff-13198ad72a3472842248bc3d0f0d3fd7R15 

Sorry for that...

**Comment by fengmk2** [comment]
test all pass on 0.10, 0.11, 0.12 and iojs

**Comment by mafintosh** [comment]
Thanks! Released in 1.3.0.

**Pull request merged**
